### PR TITLE
Implement Scrolling Function

### PR DESCRIPTION
**Pull request by Ecobbold**
Scrolling function now works, works with new fileformat too. 

Update display.c:
- compare_notes now accepts another param, the variable x, taken as m.
- Clear_all_notes: completely re-done, now wipes the screen instead.
- load_start_song: moved to reflect use in clear_all_notes

menu.c:
- Now works with new updated functions in display.c
- TWINKLE -> SONG

display_test.c:
- Make things work with scrolling, implemented screen_capture to multiple
	files, for better debugging.

clean up: header file, Also add/remove debug statements

---
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/116)

### CODE REVIEW

**Comment by uiri** [comment]
Looks good. Just clean up the dead (meaning commented out) code.

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 510 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-KgpiZEFUfIz2Q_rheWU:-KgpiZEGEXsblQsFfJHq:b-i1d1qj) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/fe08915fe5adb3726a410455094e055beb6953b8/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L510)):*
> ```C
> 	load_start_song(fbp, key, timeSignature);	
> 		
> /*	for (i=0, j=0; get_xnote(i) < END; i++, j++, notes++) {
> ```

Any reason to keep this commented out code?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c, line 163 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-Kgphemb0-Fhp9KQn3CP:-KgphemfpdveUM9yllis:b740vwh) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/fe08915fe5adb3726a410455094e055beb6953b8/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display_test.c#L163)):*
> ```C
> }
> 
> /*
> ```

I take it this comment can be removed?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 47 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-KgphtXoSUrEjSddWomL:-KgphtXp8GcXwZ3W1gZ9:b-kbhybh) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/fe08915fe5adb3726a410455094e055beb6953b8/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L47)):*
> ```C
> void play_song_menu(char* fbp, ScreenInput *si)
> {
> 	/*FILE* songfile;*/
> ```

I think this line can be removed as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-:-Kgpik_jHAqIJGvrqdwZ:b-m5cgne)*

**Comment by uiri** [comment]
Need to rebase on master; resolve conflicts.
Should be pretty straightforward to resolve - just take both sets of changes.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 110 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-Kgt9_KzpoyhmACLrb47:-Kgt9_L-T1eOVyoqQm_1:bdvsr6u) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/fe08915fe5adb3726a410455094e055beb6953b8/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L110)):*
> ```C
> 		printf("End compare notes\n");
> 		j -= m;
> 		i -= m;
> ```

might as well add in the bug fix needed here:
`notes -= m;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-:-Kgt9kyVYm4wxDzxewX7:b-zi1w57)*

**Comment by Ecobbold** [comment]
cleaned up dead code

---

Reviewed 3 of 7 files at r3.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-:-Kgu19wZRhTvg8qPOsW3:byah90h)*

**Comment by Ecobbold** [comment]
Reviewed 1 of 7 files at r3.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116)*

**Comment by uiri** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 67 at r4](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-Kgu1fv9dmlUWGGnOZKr:-Kgu1fvAuNWF9px450iN:b-ofbwq9) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/0f88355a2dff116730f77c8f866cc61e5e6a7643/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L67)):*
> ```C
> 	fbar = song->fbar;
> 	cp_pcmh = init_pcm(SAMPLE_RATE, 1);
> 	pcmh = init_pcm(SAMPLE_RATE);
> ```

This should be removed. It won't compile since `pcmh` is gone :P

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 98 at r4](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116#-Kgu1ZMydbubWD7vjPnZ:-Kgu1ZMydbubWD7vjPn_:b-cx7td1) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/0f88355a2dff116730f77c8f866cc61e5e6a7643/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L98)):*
> ```C
> 		/* Section: Audio Recording */
> 		if (recordWAV(wave, notes[i].duration, cp_pcmh)) {
> 		//if (recordWAV(wave, notes->duration)) {
> ```

should be:
`if (recordWAV(wave, notes->duration, cp_pcmh)) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116)*

**Comment by Ecobbold** [comment]
Reviewed 1 of 4 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116)*

**Comment by uiri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/116)*

**Pull request merged**
