### PR TITLE
Display

### PR DESCRIPTION
**Pull request by Ecobbold**
Updated display.c with new format:
- adding key signature support + assets
- adding time signature 
- updating all the appropriate test code
- So many Makefile changes
- Lots of clean up for new fileformat
- Cleaning up header files

---
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/95)

### CODE REVIEW

**Comment by uiri** [comment]
Good work overall. Mostly nits/style. A couple refactors here and there for math or cutting down on duplicate code.
And, we need to sort out the situation in menu. It isn't obvious to me that you broke my code.

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[Makefile, line 44 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2BXvXYaVOFZxbY95t:-Ke2BXvYXSq3ZFGzlCnM:b-8564tz) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/Makefile#L44)):*
> ```Makefile
> 	$(CC) $(CFLAGS) $^ -o $@ -lm -lasound -lsndfile
> 
> display_test: bin/format_test bin/display_test
> ```

Why do you need the `bin/format_test` program for `display_test`?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/share/eighth_n.pnm, line 0 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2Bh-7PoJ9kJ8ICulf:-Ke2Bh-8AE752pRyFycE:bkk3p49) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/share/eighth_n.pnm#L0)):*
Going to trust that the pnms are good :P 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 89 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CVRa_d57wgMGotkz:-Ke2CVRa_d57wgMGotl-:bv0lnot) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L89)):*
> ```C
> 	/*if ynote on treble clef is above B - flip the stem
> 	 150 = 90+30+30*/
> 	if(ynote < 150){
> ```

Any reason not to get rid of this if else and replace it with something like?:
```
if (ynote >= 150)
    ynote -= 105;
```

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 90 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2C92bG0-yh9dXzr1d:-Ke2C92cweTjobIiIrHG:b-dtcmif) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L90)):*
> ```C
> 	 150 = 90+30+30*/
> 	if(ynote < 150){
> 		if (value == 2){
> ```

Spaces like `) {` and `} else` pretty please?
Actually, braces aren't necessary at all for the single line blocks... (although frequently recommended if you use a macro...)

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 133 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DLxwJgU2RopcW_ph:-Ke2DLxwJgU2RopcW_pi:b-lry0zg) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L133)):*
> ```C
> }
> 
> int draw_key(char *fbp, char key){
> ```

Note to self: review this function during daytime.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 140 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2GFxcrcBMnnQ_Fuln:-Ke2GFxdhNX8KJyI1yr8:b-c4nvhb) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L140)):*
> ```C
> 	int y = 90;
> 	/*Drawing key Signature*/
> 	if (0x80 & key){
> ```

Uhhh... what happened to `symbol = 0x80 & key ? SHARP : FLAT;`
And then you can get rid of the duplicated checks on the rest of the bits.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 204 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2Ebyv5xhWK4Fy_1Ce:-Ke2Ebyv5xhWK4Fy_1Cf:b-1b63qp) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L204)):*
> ```C
> int find_octave_ynote(double freq){
> 	if (freq <= FREQS[2])
> 		return 0;/*0*/
> ```

Uh, looks like:
```
int note = find_freq(freq);
if (note < 15 || 74 < note)
    return 0;
else
    return 450 - 105 * (((note-2)/12) - 2)
```

Maybe double check my math?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 233 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2FrjM1oGz7zhHRMCf:-Ke2FrjN3Q-BUJr-Q2tI:ba82pud) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L233)):*
> ```C
> 	int note;
> 	/* for Flats */
> 	note = (ind % 12);
> ```

You *did* have math for this before, I swear...
But this is probably good enough honestly.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 270 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CyKiN5h_6vB6R47y:-Ke2CyKjeTr-vtMA_7Rf:bjypsl4) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/b2bb4aefc869acce66f6a23063ef32d1b8d2b87b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L270)):*
> ```C
> 	 * We want to re-index it so that C0 is 0 which means adding 9 for the
> 	 * calculations hence the subtraction after we have the value for ynote.
> 	 * Modulo 12 accounts for where the index is within the octave. Now we
> ```

What happened? I still see `%12` below...

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 474 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DCQP0hLi2bquI5s8:-Ke2DCQQQjze55w1iRkm:brpw6b) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L474)):*
> ```C
> 	printf("w numNotes:%d\n", song->sfh->numNotes);
> 	printf("j numBars:%d\n", song->sfh->numBars);
> 	printf("i fbar%d\n",*fbar);
> ```

Maybe remove the print statement debugging?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DZl7QfLravJDlXKc:-Ke2DZl8XCDCSsbScb2y:btk81ug) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L16)):*
> ```C
> 	//Fist Bar
> 	allNotes[i].quantumvalue = CROTCHET; 
> 	allNotes[i].frequency =261.626; 
> ```

lol sig figs... sorry :sweat_smile: 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 46 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2E5PlNGnspiyOEQa5:-Ke2E5PmW_Fn-BsEx1os:b-vp68hg) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L46)):*
> ```C
> 
> void play_song_menu(char* fbp, ScreenInput *si) {
> /*	FILE *song;
> ```

Definitely need to adjust/resolve variable declarations and dead code...

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 101 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DsGgJwfUmmO37701:-Ke2DsGhY5Jwcl9hoUtg:b-dfa796) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L101)):*
> ```C
> 	/* This run has an intentional mistake in the song*/
> 	/*	for (i = 0; i < NUM_NOTES; i++) {
> 		compare_notes(expected[i], actual[i], i, fbp);
> ```

Did this actually break? I don't see why/how...
This is kind of the core of our demo so we shouldn't comment it out the week-of...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-:-Ke2EQJvxhrBousHC3VE:b-otoc9b)*

**Comment by uiri** [comment]
*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c, line 101 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DsGgJwfUmmO37701:-Ke4Thmks_uH-czyf8_f:b-48l3s6) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/menu.c#L101)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Did this actually break? I don't see why/how...
This is kind of the core of our demo so we shouldn't comment it out the week-of...
</blockquote></details>

lolnvm this part of the menu is the bad run which we don't need anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by Ecobbold** [comment]
Review status: 23 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[Makefile, line 44 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2BXvXYaVOFZxbY95t:-Ke4eZpA2kUls6p7aW8T:bsswplo) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/Makefile#L44)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Why do you need the `bin/format_test` program for `display_test`?
</blockquote></details>

leftover from structures not working properly and trying everything. removing it.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 89 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CVRa_d57wgMGotkz:-Ke4fHO6grrkifkoPquE:bylwb6b) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L89)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Any reason not to get rid of this if else and replace it with something like?:
```
if (ynote >= 150)
    ynote -= 105;
```

</blockquote></details>

The notes flip to? I'm not sure I follow what you're suggesting I fix?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 90 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2C92bG0-yh9dXzr1d:-Ke4gG1kUEv8y48SH9mV:b-x02qsq) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L90)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Spaces like `) {` and `} else` pretty please?
Actually, braces aren't necessary at all for the single line blocks... (although frequently recommended if you use a macro...)
</blockquote></details>

waste of my time but ok.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 140 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2GFxcrcBMnnQ_Fuln:-Ke4gw_lioJis1MojyOS:bamz4yu) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L140)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Uhhh... what happened to `symbol = 0x80 & key ? SHARP : FLAT;`
And then you can get rid of the duplicated checks on the rest of the bits.
</blockquote></details>

kbut it works right now and reformatting it will take a lot of time, is this really necessary? 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 204 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2Ebyv5xhWK4Fy_1Ce:-Ke4hF2ho6x4fcwsubna:b5s8f5r) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L204)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Uh, looks like:
```
int note = find_freq(freq);
if (note < 15 || 74 < note)
    return 0;
else
    return 450 - 105 * (((note-2)/12) - 2)
```

Maybe double check my math?
</blockquote></details>

It's set up now so that if It needs to change depending on what I want to return with octave. 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 270 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CyKiN5h_6vB6R47y:-Ke4hv5s1-Kvelcpyr7J:b2ni4qz) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/b2bb4aefc869acce66f6a23063ef32d1b8d2b87b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L270)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

What happened? I still see `%12` below...
</blockquote></details>

idk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by uiri** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 89 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CVRa_d57wgMGotkz:-Ke5V26TtTYbuloe7WVP:b-ibb4bb) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L89)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

The notes flip to? I'm not sure I follow what you're suggesting I fix?
</blockquote></details>

derp NVM

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 133 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2DLxwJgU2RopcW_ph:-Ke5VB0Ug7aTypbeMXx3:b-7rl0jd) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L133)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Note to self: review this function during daytime.
</blockquote></details>

done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 140 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2GFxcrcBMnnQ_Fuln:-Ke5VNbPvuAiuTykvx2w:biaryeb) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L140)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

kbut it works right now and reformatting it will take a lot of time, is this really necessary? 
</blockquote></details>

Yes, This is a lot of duplicated code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by uiri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 270 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CyKiN5h_6vB6R47y:-Ke5YJLkJE7T1OOYcS0c:byr4qqe) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/b2bb4aefc869acce66f6a23063ef32d1b8d2b87b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L270)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

idk
</blockquote></details>

Can you add in the removed comment lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by uiri** [comment]
Reviewing my code that was reviewed by you.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-:-Ke6JY6DDKa1rHCGKcs-:b-ntvc8r)*

**Comment by Ecobbold** [comment]
Reviewed 1 of 25 files at r1, 1 of 3 files at r2, 2 of 5 files at r3.
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 270 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2CyKiN5h_6vB6R47y:-Ke6wdZX3Wvs2-YQHRJA:boj38y) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/b2bb4aefc869acce66f6a23063ef32d1b8d2b87b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L270)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Can you add in the removed comment lines?
</blockquote></details>

Now hat I'm thinking about it, this could totally be an Emilie&vim@night bug. Fixing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by Ecobbold** [comment]
Review status: 25 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 140 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2GFxcrcBMnnQ_Fuln:-Ke70AWBd-Z_spulbQET:b-ce9404) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L140)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Yes, This is a lot of duplicated code
</blockquote></details>

actually it's not because of ynote. It's coming back to me, the sharp at 0x20 is not the same as the flat. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by Ecobbold** [comment]
Reviewed 19 of 25 files at r1, 3 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95)*

**Comment by uiri** [comment]
Ugh that merge commit. ~ whatever no big deal ~
Also apparently I can dismiss you from discussions and resolve them even though you didn't mark satisfied?? Hopefully only from discussions which I start.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 140 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-Ke2GFxcrcBMnnQ_Fuln:-Ke7EihtMTIdbl7UbN4g:b-x098cq) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff0a93b013782017c435306fef218e2fc248003b/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L140)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

actually it's not because of ynote. It's coming back to me, the sharp at 0x20 is not the same as the flat. 
</blockquote></details>

Right. I'm a derp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/95#-:-Ke7Eehbuu88B0orKWKD:b-gvd0uv)*

**Pull request merged**
