### PR TITLE
Trouble bar feedback

### PR DESCRIPTION
**Pull request by tchin018**
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/104)

### CODE REVIEW

**Comment by uiri** [comment]
You need to `git rebase -i master` and remove everything except for f5a7f66 and 43912d4 and then `git push -f`
And *then* perform your fixes according to my comments :smile: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 458 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9AktQdLJTtY6rk2SE:-Kf9AktRzKhQovUqcrmF:b-btna9b) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L458)):*
> ```C
> 	fbar = song->fbar;
> 
> 	numWrongNotes = malloc(sizeof(int) * song->sfh->numNotes);
> ```

Shouldn't this be `song->sfh->numBars` ?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 473 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9AzmHY6b3yCBtS-k4:-Kf9AzmIyCZMrK_eVQ7V:b-nxir7y) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L473)):*
> ```C
> 			    		worstBar = fbar;
> 			}
> 			else {
> ```

`} else {` please.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 480 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9BA6w5qGy80G-bIkL:-Kf9BA6w5qGy80G-bIkM:bjkwe9z) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L480)):*
> ```C
> 			i = 0;
> 
>      	        }
> ```

Indentation...
A general whitespace cleanup would be nice but this line in particular needs to be fixed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 487 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9BPX8z1TcON_Ef_Kb:-Kf9BPX9K9yOr6sGW4Xm:b-jf3mnl) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L487)):*
> ```C
> 		}
> 
> 		notes++;
> ```

Is this variable used anywhere? I think you can remove it from this function.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 498 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9CUBqZPEW7PeZvfzj:-Kf9CUBqZPEW7PeZvfzk:bpbqnp6) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L498)):*
> ```C
> }
> 
> void draw_worst_bar(char* fbp, Bar* worstBar, Note* notes, Song* song) {
> ```

Do we need this function in master?
I think we're going to add a µGFX page for feedback instead that will jump to the worst bar...

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 518 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9CRtT-u9ouDhGs9pY:-Kf9CRtT-u9ouDhGs9pZ:b-96tohb) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L518)):*
> ```C
> 			draw_note(j, ynote, fbp, colour, time);
> 					
> 	        }
> ```

Indentation.
Just select everything in Emacs, hit the tab key and be done with it lol.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 520 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9DOHjqkg2aqHa5CrT:-Kf9DOHksY3_JiWKIn1S:bglxnis) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L520)):*
> ```C
> 	        }
> 
> 		if (i == fbar->notes) {
> ```

This block should be before your other block. I think this is the cause of at least one of your off-by-one type errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-:-Kf8m-fUeydMVNnNn8zK:b8spm9)*

**Comment by tchin018** [comment]
Done.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 458 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9AktQdLJTtY6rk2SE:-KfDCCe6aM5GQbTVBdyQ:b-6s0bsi) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L458)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Shouldn't this be `song->sfh->numBars` ?
</blockquote></details>

yeah, it should. 

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 473 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9AzmHY6b3yCBtS-k4:-KfDIiJ-aLC5LvaE4D7g:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L473)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

`} else {` please.
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 480 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9BA6w5qGy80G-bIkL:-KfDIbWE7AapmXYlc1rF:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L480)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Indentation...
A general whitespace cleanup would be nice but this line in particular needs to be fixed.
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 487 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9BPX8z1TcON_Ef_Kb:-KfDEYONt_80dYqnDGjU:b-pmycdh) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L487)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Is this variable used anywhere? I think you can remove it from this function.
</blockquote></details>

I use it to iterate through the song bars. It's supposed to be used in the if statement no?
`if (i == fbar->notes)` 
Should I still remove it?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 498 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9CUBqZPEW7PeZvfzj:-KfDFVn3VtkCDM6YXCb4:bbi1lec) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L498)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Do we need this function in master?
I think we're going to add a µGFX page for feedback instead that will jump to the worst bar...
</blockquote></details>

If we do that, then I guess we won't need to highlight the notes. I've left it for now. Let me know if it should go.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 518 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9CRtT-u9ouDhGs9pY:-KfDI7gUoy3Tc-Hb1rSl:bwauwse) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L518)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Indentation.
Just select everything in Emacs, hit the tab key and be done with it lol.
</blockquote></details>

I did that, the tabs looks really different now, lol. Not sure why.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 520 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9DOHjqkg2aqHa5CrT:-KfDGmJkWHaUM2IbX_pl:bb70bl3) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L520)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

This block should be before your other block. I think this is the cause of at least one of your off-by-one type errors.
</blockquote></details>

O.k.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-:-KfDImA4uAJfeFNiHF3V:b-896fix)*

**Comment by uiri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 487 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9BPX8z1TcON_Ef_Kb:-KfHTbULVoYyZljtWyaJ:bl2kipk) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L487)):*
<details><summary><i>Previously, tchin018 wrote…</i></summary><blockquote>

I use it to iterate through the song bars. It's supposed to be used in the if statement no?
`if (i == fbar->notes)` 
Should I still remove it?
</blockquote></details>

`notes` is not the same thing as `fbar->notes`
`notes` is a parameter to the function which doesn't get used. I still think it should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104)*

**Comment by uiri** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c, line 498 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104#-Kf9CUBqZPEW7PeZvfzj:-KfPQGhQL1Ly8rNco113:b-s3ntg3) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/e573bc6935c87ddc46a5700e40ad99f34cbe517e/bbb/meta-bbb/recipes-core/trebletrouble/files/src/display.c#L498)):*
<details><summary><i>Previously, tchin018 (Tejan C) wrote…</i></summary><blockquote>

If we do that, then I guess we won't need to highlight the notes. I've left it for now. Let me know if it should go.
</blockquote></details>

I'm thinking it should go.
Maybe run a quick test first thing tomorrow (i.e. go straight for loading up an SD card and testing on the board) and if it highlights the correct notes now, it can stay. Last I saw it wasn't even finding the right bar :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104)*

**Comment by uiri** [comment]
Ping @tchin018 what is the status of this PR?

**Comment by uiri** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/104)*

**Pull request merged**
