### PR TITLE
Song format

### PR DESCRIPTION
**Pull request by danrsles**
Created a song format , and used Twinkle Twinkle Little Star as a demo piece.
Working test of the binary file being read was also created. 
Appropriate changes to the MakeFile were made.

---
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/88)

### CODE REVIEW

**Comment by uiri** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/share/TwinkleTwinkle.bin, line 0 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT-EBCAE6uTEekSSRZ:-KdT-EBCAE6uTEekSSR_:b-zccw22) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/share/TwinkleTwinkle.bin#L0)):*
Just going to assume that this binary is valid ;)

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 3 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1UH8aJeXVvGCs8Ev:-KdT1UH9Uc_OCMCHtc6w:b-3c431q) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L3)):*
> ```C
> #include <stdio.h>
> #include "fileFormat.h"
> void makeBin() {
> ```

If this file's purpose is to help us generate song files, it might be more useful to take a MIDI file as input or give an easy way for us to manually enter some notes to create a song.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 125 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1hxVW921JA9BvB0Z:-KdT1hxWvzUhBvf8fn7i:b-l3f4py) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L125)):*
> ```C
> 	
> 	/* Create the file */
> 	FILE *fh = fopen (TWINKLE_FILENAME, "wb+");
> ```

Ideally this would be easily set as a parameter to the function.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 15 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2fBCzkK1bBnMVe-s:-KdT2fBDS_nCb1rt1_xo:bm9vk8x) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L15)):*
> ```objc
> typedef struct {
> 	/*Will be defined by a helper function*/
> 	int duration;
> ```

Does this make sense given the code in tone and audio_recorder that operate using floating point durations in seconds?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2gFTiUCei4epdelo:-KdT2gFTiUCei4epdelp:b-p6mumy) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L16)):*
> ```objc
> 	/*Will be defined by a helper function*/
> 	int duration;
> 	float frequency;
> ```

Up to Émilie whether she wants this to be an int index or a float pitch.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 20 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3yxkVQk_EO1xnVYv:-KdT3yxlafkopGvOVveI:bgflomm) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L20)):*
> ```objc
> 	/*dotted will be 1 or 0*/
> 	int dotted;
> 	}note;
> ```

Capitalize the struct to Note please.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 25 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3sN5ma_dX_-vK59l:-KdT3sN6KB0lSYmuGiIn:b-1udoic) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L25)):*
> ```objc
> typedef struct{
> 	int numNotes;
> }bar;
> ```

Is there a reason to wrap this in a struct?
Perhaps `typedef int Bar`?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 34 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4DNhRwE1DkRFFZ7F:-KdT4DNit-i8IlOMApyj:bia5m7l) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L34)):*
> ```objc
> 	unsigned char timeSignature;
> 	char name[50];
> }songFormatHeader;
> ```

capitalize

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 41 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4EXQg-5IOKnXmwYq:-KdT4EXQg-5IOKnXmwYr:bia5m7l) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L41)):*
> ```objc
> 	bar * fbar;
> 	
> }song;
> ```

capitalize

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 9 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT32nmvqZzHC8GSClt:-KdT32nn2Off11FZBdmf:bygxa9f) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L9)):*
> ```C
> 
> int main(int argc, char** argv){
> 	
> ```

Given that you like the extra line between the function signature and the function body, perhaps consider putting the opening brace on that line? (see: my reformatting of simpleAlsa).

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 8 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4NKE3W2b3kwuxc9M:-KdT4NKE3W2b3kwuxc9N:b-3er5jh) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L8)):*
> ```C
> void createTwinkle()
> {
> 	makeBin();
> ```

Is there a reason to wrap `makeBin()` like this?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3XSksEdG4TaB_pFm:-KdT3XSlHUOdYEI0Fmel:b-hj5jrs) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L16)):*
> ```C
> 	note *notes;
> 	FILE * twinkle;
> 	twinkle = fopen(TWINKLE_FILENAME,"rb");
> ```

I think the filename should be a parameter to the function.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 56 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4Yb3j44EIV4-fp46:-KdT4Yb3j44EIV4-fp47:bmcudf2) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L56)):*
> ```C
> 
> //Free Song 
> void freeSong(song * ttls)
> ```

This is kind of confusing. Usually when you pass a `TYPE` pointer to a `freeTYPE` function, that function calls `free(...)` on that pointer.
Of course, in your example the struct is allocated on the stack. This may or may not be the case when we use this in the actual application though.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 103 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3NZFg4d5eF42EE3S:-KdT3NZGpJmIO8YOmBts:b-b47hq6) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L103)):*
> ```C
> }
> 
> unsigned char getTS(song *ttls)
> ```

I think `getTimeSig` would be a little bit more explanatory.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/Twinkle.bin, line 0 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1GytQkURFUS67TcB:-KdT1GyuBYzqEkb0zpfv:bfpoqub) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/Twinkle.bin#L0)):*
Remove this file? source code only in `src` please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by danrsles** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 125 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1hxVW921JA9BvB0Z:-KdWm-48Nfmx3aBm4yt-:bwis4yu) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L125)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Ideally this would be easily set as a parameter to the function.
</blockquote></details>

I agree with this , this is version one basically

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 15 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2fBCzkK1bBnMVe-s:-KdWmFTJo0vu09m27Gr2:buv46rt) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L15)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Does this make sense given the code in tone and audio_recorder that operate using floating point durations in seconds?
</blockquote></details>

I can change it to floating points

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2gFTiUCei4epdelo:-KdWmCsOmTQ0x5QJt1nC:b-yvs4kw) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L16)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Up to Émilie whether she wants this to be an int index or a float pitch.
</blockquote></details>

Emilie let me know

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 20 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3yxkVQk_EO1xnVYv:-KdWmLjtswkJNW-K1QSo:bb7efny) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L20)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Capitalize the struct to Note please.
</blockquote></details>

cool

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 34 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4DNhRwE1DkRFFZ7F:-KdWmaYzYQcPfW-SXc3n:b-q8ilnv) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L34)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

capitalize
</blockquote></details>

gotcha

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 41 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4EXQg-5IOKnXmwYq:-KdWmcPucGscPWx-P3ip:b-q8ilnv) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L41)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

capitalize
</blockquote></details>

gotcha

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 9 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT32nmvqZzHC8GSClt:-KdWml6jxH7H9iVwYlmm:bkjxpv0) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L9)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Given that you like the extra line between the function signature and the function body, perhaps consider putting the opening brace on that line? (see: my reformatting of simpleAlsa).
</blockquote></details>

alright

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 8 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4NKE3W2b3kwuxc9M:-KdWmpxQpz50nOgEPdMS:b-nul8h3) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L8)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Is there a reason to wrap `makeBin()` like this?
</blockquote></details>

More so for myself. As I was formatting the code, I just figured since this is specific only to twinkle twinkle. Will Change on my following upload

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3XSksEdG4TaB_pFm:-KdWnAtLe9fRqkK5uYVy:b-cstnkg) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L16)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

I think the filename should be a parameter to the function.
</blockquote></details>

I agree

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 103 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3NZFg4d5eF42EE3S:-KdWnIwU2xOQC48maoAn:b-wmovsm) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L103)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

I think `getTimeSig` would be a little bit more explanatory.
</blockquote></details>

Was just trying to get a print statement to fit in one line, for printHeader()

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/Twinkle.bin, line  at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1GytQkURFUS67TcB:-KdWnVLQRxXof1J6lF2H:bxxgu1b) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/Twinkle.bin#L)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Remove this file? source code only in `src` please.
</blockquote></details>

Cool Cool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by Ecobbold** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 8 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdWwvTScahprUpBzQxH:-KdWwvTTckzZi7WfYBut:b-2uzvp7) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L8)):*
> ```C
> 	int j;
> 	songFormatHeader sfh = {100,4,14,'C',51,"twinkle twinkle little star"};
> 	//12 bars of twinkle twinkle 
> ```

12 bars?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2gFTiUCei4epdelo:-KdWwIvIrozcCDwXfoDB:b-b2hjj4) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L16)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

Emilie let me know
</blockquote></details>

Keeping it consistent would be nice. We use double freq in display.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by Ecobbold** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 7 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdX31AUw5VzeBh7NTf6:-KdX31AW1OE4-xAKFaId:b-o03j79) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L7)):*
> ```C
> 	int i;
> 	int j;
> 	songFormatHeader sfh = {100,4,14,'C',51,"twinkle twinkle little star"};
> ```

Change key 'C' to 'C_MAJ' and add macros found in the display branch, display.h (lines 41-70) as discussed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by uiri** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 15 at r2](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdY0a4uv22CraI6HiPi:-KdY0a4vDy3-81ikwIr8:bjdwb90) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/1d64f9bb3416116a26989ecfe73f360011ad1d67/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L15)):*
> ```C
> 	i=0;
> 	j=0;
> 	//Fist Bar
> ```

I feel like this code could be re-organized.
For instance, start off with `allBars[j] = 0;` and add `allBars[j]++;` at the end of each note block.
And then on the next bar, add `allBars[++j] = 0;`

Does `allNotes[i] = {CROTCHET, 261.6, millisec(sfh.bpm, CROTCHET), 0};` work? Otherwise, it might be good to wrap that up into a function or macro.

The code really should be able to automatically set up the bars based off of the notes input.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 56 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4Yb3j44EIV4-fp46:-KdY-rwNd5veMOtFDAX7:bkqjyhd) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L56)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

This is kind of confusing. Usually when you pass a `TYPE` pointer to a `freeTYPE` function, that function calls `free(...)` on that pointer.
Of course, in your example the struct is allocated on the stack. This may or may not be the case when we use this in the actual application though.
</blockquote></details>

This still doesn't free `ttls` itself...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by danrsles** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 7 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdX31AUw5VzeBh7NTf6:-Kdb1K5cKMe5WsqBUjkJ:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L7)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

Change key 'C' to 'C_MAJ' and add macros found in the display branch, display.h (lines 41-70) as discussed
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 125 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT1hxVW921JA9BvB0Z:-KdXGqKg-W0CNSfHWmXc:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L125)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

I agree with this , this is version one basically
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 15 at r2](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdY0a4uv22CraI6HiPi:-Kdb1YWqL1qUqKIxxUJU:b-8nj23) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/1d64f9bb3416116a26989ecfe73f360011ad1d67/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L15)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

I feel like this code could be re-organized.
For instance, start off with `allBars[j] = 0;` and add `allBars[j]++;` at the end of each note block.
And then on the next bar, add `allBars[++j] = 0;`

Does `allNotes[i] = {CROTCHET, 261.6, millisec(sfh.bpm, CROTCHET), 0};` work? Otherwise, it might be good to wrap that up into a function or macro.

The code really should be able to automatically set up the bars based off of the notes input.
</blockquote></details>

I know will, but this is just for twinkle twinkle.This code was meant so that emilie can start working on a single file. If she wants to start working with this and the display this code is good for now. Working on a more general one will take me a bit more time.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 15 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2fBCzkK1bBnMVe-s:-KdXGuE8p5Zv8VxVVSd3:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L15)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

I can change it to floating points
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 9 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT32nmvqZzHC8GSClt:-KdXGxuZoEQ8h842g32A:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L9)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

alright
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 8 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4NKE3W2b3kwuxc9M:-KdXGzNvT0Zm5i-BIQLf:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L8)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

More so for myself. As I was formatting the code, I just figured since this is specific only to twinkle twinkle. Will Change on my following upload
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT3XSksEdG4TaB_pFm:-KdXH-TPHCyWYZKuwQ58:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L16)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 56 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4Yb3j44EIV4-fp46:-Kdb2salrjSa59Zykx44:b-cuqd1i) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L56)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

This still doesn't free `ttls` itself...
</blockquote></details>

sorry will I am confused . How do you propose I do this?, like make a third malloc()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by uiri** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 7 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdX31AUw5VzeBh7NTf6:-KdbJo103_H95p1RkToe:b-vnamx8) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L7)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Emilie you need to resolve this :P

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 15 at r2](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdY0a4uv22CraI6HiPi:-KdbK-fBdinn8b51_qrr:b-8slv3i) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/1d64f9bb3416116a26989ecfe73f360011ad1d67/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L15)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

I know will, but this is just for twinkle twinkle.This code was meant so that emilie can start working on a single file. If she wants to start working with this and the display this code is good for now. Working on a more general one will take me a bit more time.
</blockquote></details>

OK since it is a simple refactor I guess it doesn't matter if you do it now or later.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 16 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT2gFTiUCei4epdelo:-KdbKYn9Jv_O_sbE8gsn:be5rppm) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L16)):*
<details><summary><i>Previously, Ecobbold (Emilie Cobbold) wrote…</i></summary><blockquote>

Keeping it consistent would be nice. We use double freq in display.c
</blockquote></details>

float is good enough. Keeps the struct compact, still uses a floating point number like a double.

Emilie, can you accept this if you're happy with it?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 56 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT4Yb3j44EIV4-fp46:-KdbKFiOii3y7Q19BNet:b-o3weky) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L56)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

sorry will I am confused . How do you propose I do this?, like make a third malloc()?
</blockquote></details>

Yeah, per my original comment, I think that ttls should be `malloc`'d... Sorry if that was unclear before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by Ecobbold** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Comment by uiri** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/share/TwinkleTwinkle.bin, line  at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdT-EBCAE6uTEekSSRZ:-KdgZTr9NEmwI6cKp25G:b-2vvjr8) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/8d5acf16fa427e29411f06bf215a08c480634dba/bbb/meta-bbb/recipes-core/trebletrouble/files/share/TwinkleTwinkle.bin#L)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Just going to assume that this binary is valid ;)
</blockquote></details>

Do I want to know why this changed..?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 11 at r3](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88#-KdgZ_KYlPfZ2VBFzaEA:-KdgZ_KZyqOZF-SgiXU8:bk8c6wu) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/ff1d370c85b921fc2b8cfaa8c2d875327f028917/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L11)):*
> ```C
> {
> 	Song * ttls;
> 	ttls =(Song *)malloc (sizeof(ttls));
> ```

No need for the cast. This is C not C++

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/88)*

**Pull request merged**
