### PR TITLE
Song format

### PR DESCRIPTION
**Pull request by danrsles**
FIle format has been changed so that we can now add songs by filling out all information on a txt file. And a .bin will be created by running the test file.

In order to add a file follow song.txt as an example and do a call to 
./format_test  song.txt
where the argument is the name of your text file created.

***Note that song.txt has a single string on every line followed by a new line.

---
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/107)

### CODE REVIEW

**Comment by uiri** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 93 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRxYDuYm_sSGfsJSHi:-KfRxYDyza46YtnRsMAG:bgp2as9) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L93)):*
> ```C
> 
> 	/* opening file for reading */
> 	fp = fopen(filename , "r");
> ```

Change to `fp = stdin;` ?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 121 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRxjBCEqDhB6xkyv_s:-KfRxjBFfLyKA_5IcPZY:b5q34y8) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L121)):*
> ```C
> 		
> 	for (j = 0;j<sfh.numBars;j++)
> 		{
> ```

BTW opening brace should go on the same line. And closing brace should be at the same level of indentation as the `for` or `if` or whatever.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 12 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRyYE1qlnBpgwLRzQf:-KfRyYE4lUXPoX6E13qd:b-59m9fy) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L12)):*
> ```objc
> 
> #define TWINKLE_FILENAME "TwinkleTwinkle.bin"
> #define DEMO "demo.bin"
> ```

Is this used anywhere?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 64 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRyg4Pp1kozzbTAl6K:-KfRyg4SsRWFfTZ81mWa:blsui51) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L64)):*
> ```objc
> 	int numNotes;
> 	char key;
> 	unsigned char timeSignature;//This is for ASCII code
> ```

FYI This is just a byte which we pack the time sig info into...
Not really anything to do with ASCII other than a coincidence for 4/4 time.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 85 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfS-b_pbVROb9UTP8Xx:-KfS-b_tqL0uIJoy6Wlx:b-da4s8t) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L85)):*
> ```objc
> char eval(int key);
> 
> int find_quantum_value(char * check,char  *str1,char  *str2,char *str3,char *str4,char *str5,char *str6);
> ```

Where is this defined?
Also, is there any utility in exposing `rl` and `eval` outside of fileFormat.c ?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 105 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfS-mjZcLb1YfooAekF:-KfS-mjafaeh9Mt9Bt1h:b-dik2xu) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L105)):*
> ```C
> 	//read the Bars and the notes in the bar
> 	for (i = 0 ; i< ttls->sfh->numBars;i++) {
> 		for (j = 0; j < ttls->fbar->notes-1 ;j++) {
> ```

why -1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107)*

**Comment by uiri** [comment]
Ping @drosa what is the status of this PR?

**Comment by danrsles** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 93 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRxYDuYm_sSGfsJSHi:-KftKvZqU4eZPuJCiRIw:bjn8l7a) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L93)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Change to `fp = stdin;` ?
</blockquote></details>

i have questions for tommorrow

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c, line 121 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRxjBCEqDhB6xkyv_s:-KftK4d3B3gZ_dJyR4gh:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.c#L121)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

BTW opening brace should go on the same line. And closing brace should be at the same level of indentation as the `for` or `if` or whatever.
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 12 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRyYE1qlnBpgwLRzQf:-KfrbRWuR0Y1Qva4Xk-z:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L12)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Is this used anywhere?
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 64 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfRyg4Pp1kozzbTAl6K:-KfrgQtDCkjJu3WrSlNG:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L64)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

FYI This is just a byte which we pack the time sig info into...
Not really anything to do with ASCII other than a coincidence for 4/4 time.
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h, line 85 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfS-b_pbVROb9UTP8Xx:-KfrgJtqzYirNdvUw4Pq:b9no36n) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat.h#L85)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

Where is this defined?
Also, is there any utility in exposing `rl` and `eval` outside of fileFormat.c ?
</blockquote></details>

so do you want me to put them in the fileFormat .c ??

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c, line 105 at r1](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-KfS-mjZcLb1YfooAekF:-Kfratsv3fQh-pj-UaG6:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/77aa087bbe1268647b9ee9362bd7cc3827e8c3a5/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileRead.c#L105)):*
<details><summary><i>Previously, uiri (W Pearson) wrote…</i></summary><blockquote>

why -1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107)*

**Comment by uiri** [comment]
Looks like 77aa087 got lost in the rebase...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-:-KfxBz5WJ9oR4a31TmO-:b361oan)*

**Comment by uiri** [comment]
Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 12 at r4](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-Kg-cJ9Z-byNviWB-FEY:-Kg-cJ9aJsjtDfKGjP7U:b-rmmquq) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/a5c6ff5877120b0f812128f4c7bbffc3d1c20a27/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L12)):*
> ```C
> {
> 	Song * ttls;
> 	char tname [50] ;
> ```

What is the purpose of this variable? Why not just use argv[1] directly?

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 24 at r4](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-Kg-ce-4jEZaposPchgg:-Kg-ce-6XfqGAl8lkFb9:bbub76t) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/a5c6ff5877120b0f812128f4c7bbffc3d1c20a27/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L24)):*
> ```C
> 	for(i= 0;i<ttls->sfh->numNotes;i++){
> 	printNote(notes);
> 	notes++;
> ```

lolindentation

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c, line 32 at r4](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107#-Kg-caVPT7z3FibbOz9z:-Kg-caVTRuQAsLoffR22:b-sf1ike) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/a5c6ff5877120b0f812128f4c7bbffc3d1c20a27/bbb/meta-bbb/recipes-core/trebletrouble/files/src/fileFormat_test.c#L32)):*
> ```C
> 	//printNote(notes);
> 	//notes++;
> 	//parseBar(ttls,notes);
> ```

is there a reason to keep this commented out code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107)*

**Comment by uiri** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/107)*

**Pull request merged**
