### PR TITLE
Tone

### PR DESCRIPTION
**Pull request by uiri**
Reorganized the tone module. The tone_test works with a wave struct and actually produces correct results.

---
This change is [Reviewable](https://reviewable.io/reviews/trebletrouble/trebletrouble/85)

### CODE REVIEW

**Comment by danrsles** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/audio_recorder.c, line 119 at r5](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-KdXRVrNH8JDkG0l_zdK:-KdXRVrNH8JDkG0l_zdL:baip6f1) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/dce2bef94f68173f3944c038731e973ce5df2834/bbb/meta-bbb/recipes-core/trebletrouble/files/src/audio_recorder.c#L119)):*
> ```C
>     err = snd_pcm_readi(handle, buffer, frames);
>     if (err >= 0) {
>       totalFrames += err;
> ```

Delete unused variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
Reviewed 1 of 6 files at r5.
Review status: 1 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
Reviewed 2 of 5 files at r4, 5 of 6 files at r5.
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/tone.c, line 63 at r5](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-KdX_zpnbodajEMT3JlM:-KdX_zpnbodajEMT3JlN:b-s25wal) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/dce2bef94f68173f3944c038731e973ce5df2834/bbb/meta-bbb/recipes-core/trebletrouble/files/src/tone.c#L63)):*
> ```C
> 
>   for (i = 0; i < wave->nSamples; i++) {
>     waveData[i] = ((float)((int*)wave->data)[i]) / (1<<(wave->header.bitsPerSample-1));
> ```

why do you shift the bits by 1 and subtract one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
Reviewed 2 of 3 files at r3.
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
Reviewed 1 of 3 files at r3, 1 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by uiri** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/audio_recorder.c, line 119 at r5](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-KdXRVrNH8JDkG0l_zdK:-KdY1dhT1jf3q8LgGwBy:b-896fix) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/dce2bef94f68173f3944c038731e973ce5df2834/bbb/meta-bbb/recipes-core/trebletrouble/files/src/audio_recorder.c#L119)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

Delete unused variables
</blockquote></details>

Done.

---

*[bbb/meta-bbb/recipes-core/trebletrouble/files/src/tone.c, line 63 at r5](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-KdX_zpnbodajEMT3JlM:-KdY5C_UTf2-ZHBJM732:b-qvifkv) ([raw file](https://github.com/trebletrouble/trebletrouble/blob/dce2bef94f68173f3944c038731e973ce5df2834/bbb/meta-bbb/recipes-core/trebletrouble/files/src/tone.c#L63)):*
<details><summary><i>Previously, danrsles wrote…</i></summary><blockquote>

why do you shift the bits by 1 and subtract one
</blockquote></details>

Signed 16-bit value has to be converted into a float between -1.0 and +1.0. The bitshift and subtraction calculates the maximum possible positive value. Dividing by that normalizes the float to the correct range.

See waveAddSample for the conversion going in the other direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85)*

**Comment by danrsles** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-:-Kdg_kaDGyx7zu8FfnSY:bnfp4nl)*

**Comment by danrsles** [comment]
OK

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trebletrouble/trebletrouble/85#-:-KdgaLXoCL1aPu7tsitN:b32w0x)*

**Comment by uiri** [comment]
Oh shit. Whoops.

**Pull request closed without merging**
